import { supabase } from '@/integrations/supabase/client';

export type GenerationStrategy = 'auto' | 'svg' | 'ai-openai' | 'ai-gemini' | 'wiki-only';

export interface NumberImage {
  number: number;
  imageUrl: string | null;
  pageUrl: string;
  cached?: boolean;
  error?: string;
  aiGenerated?: boolean;
  skipScrape?: boolean;
  autoGenerated?: boolean;
  composed?: boolean;
  svgGenerated?: boolean;
}

export interface ScrapeResponse {
  success: boolean;
  error?: string;
  data?: NumberImage[];
}

export interface GenerateResponse {
  success: boolean;
  error?: string;
  imageUrl?: string;
  aiGenerated?: boolean;
  svgGenerated?: boolean;
}

export const numberblocksApi = {
  async scrapeImages(startNumber: number = 1, endNumber: number = 20, strategy: GenerationStrategy = 'auto'): Promise<ScrapeResponse> {
    const isSingleNumber = startNumber === endNumber;
    
    // For non-auto strategies on single numbers, call the specific generator directly
    if (isSingleNumber && strategy !== 'auto' && strategy !== 'wiki-only') {
      let functionName: string;
      if (strategy === 'svg') functionName = 'generate-svg-numberblock';
      else if (strategy === 'ai-gemini') functionName = 'generate-gemini-numberblock';
      else functionName = 'generate-numberblock'; // ai-openai

      const { data, error } = await supabase.functions.invoke(functionName, {
        body: { number: startNumber, force: true },
      });

      if (error) {
        return { success: false, error: error.message };
      }

      if (data?.success && data?.imageUrl) {
        return {
          success: true,
          data: [{
            number: startNumber,
            imageUrl: data.imageUrl,
            pageUrl: `https://numberblocks.fandom.com/wiki/${startNumber}`,
            aiGenerated: data.aiGenerated || false,
            svgGenerated: data.svgGenerated || false,
          }],
        };
      }
      return { success: false, error: data?.error || 'Generation failed' };
    }

    // For auto/wiki-only, use the scraper with strategy param
    const { data, error } = await supabase.functions.invoke('scrape-numberblocks', {
      body: { startNumber, endNumber, isSingleNumber, strategy },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async generateWithAI(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-numberblock', {
      body: { number },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async regenerate(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-numberblock', {
      body: { number, force: true },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async generateSVG(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-svg-numberblock', {
      body: { number },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async generateWithGemini(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-gemini-numberblock', {
      body: { number },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },
};
