import { supabase } from '@/integrations/supabase/client';

export interface NumberImage {
  number: number;
  imageUrl: string | null;
  pageUrl: string;
  cached?: boolean;
  error?: string;
  aiGenerated?: boolean;
  skipScrape?: boolean;
  autoGenerated?: boolean;
}

export interface ScrapeResponse {
  success: boolean;
  error?: string;
  data?: NumberImage[];
}

export interface GenerateResponse {
  success: boolean;
  error?: string;
  imageUrl?: string;
  aiGenerated?: boolean;
}

export const numberblocksApi = {
  async scrapeImages(startNumber: number = 1, endNumber: number = 20): Promise<ScrapeResponse> {
    const isSingleNumber = startNumber === endNumber;
    
    const { data, error } = await supabase.functions.invoke('scrape-numberblocks', {
      body: { startNumber, endNumber, isSingleNumber },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async generateWithAI(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-numberblock', {
      body: { number },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },
};
