import { supabase } from '@/integrations/supabase/client';

export type GenerationStrategy = 'auto' | 'svg' | 'compose' | 'ai-openai' | 'ai-gemini' | 'wiki-only';

export const ALL_STRATEGIES: { value: GenerationStrategy; label: string; emoji: string }[] = [
  { value: 'wiki-only', label: 'Wiki', emoji: '📚' },
  { value: 'svg', label: 'SVG', emoji: '📐' },
  { value: 'compose', label: 'Compose', emoji: '🧩' },
  { value: 'ai-openai', label: 'OpenAI', emoji: '🎨' },
  { value: 'ai-gemini', label: 'Gemini', emoji: '✨' },
];

export interface CompareResult {
  strategy: GenerationStrategy;
  label: string;
  emoji: string;
  image: NumberImage | null;
  loading: boolean;
  error?: string;
}

export type GenerationMethod = 'openai' | 'gemini' | undefined;

export interface NumberImage {
  number: number;
  imageUrl: string | null;
  pageUrl: string;
  cached?: boolean;
  error?: string;
  aiGenerated?: boolean;
  generationMethod?: GenerationMethod;
  skipScrape?: boolean;
  autoGenerated?: boolean;
  composed?: boolean;
  svgGenerated?: boolean;
}

export interface ScrapeResponse {
  success: boolean;
  error?: string;
  data?: NumberImage[];
}

export interface GenerateResponse {
  success: boolean;
  error?: string;
  imageUrl?: string;
  aiGenerated?: boolean;
  generationMethod?: GenerationMethod;
  svgGenerated?: boolean;
}

export const numberblocksApi = {
  async scrapeImages(startNumber: number = 1, endNumber: number = 20, strategy: GenerationStrategy = 'auto'): Promise<ScrapeResponse> {
    const isSingleNumber = startNumber === endNumber;
    
    // For non-auto strategies on single numbers, call the specific generator directly
    if (isSingleNumber && strategy !== 'auto' && strategy !== 'wiki-only') {
      let functionName: string;
      if (strategy === 'svg') functionName = 'generate-svg-numberblock';
      else if (strategy === 'compose') functionName = 'compose-numberblock';
      else if (strategy === 'ai-gemini') functionName = 'generate-gemini-numberblock';
      else functionName = 'generate-numberblock'; // ai-openai

      const { data, error } = await supabase.functions.invoke(functionName, {
        body: { number: startNumber, force: true },
      });

      if (error) {
        return { success: false, error: error.message };
      }

      if (data?.success && data?.imageUrl) {
        // Determine generationMethod from the strategy or from the response
        let generationMethod: GenerationMethod = data.generationMethod;
        if (!generationMethod) {
          if (strategy === 'ai-openai') generationMethod = 'openai';
          else if (strategy === 'ai-gemini') generationMethod = 'gemini';
        }
        return {
          success: true,
          data: [{
            number: startNumber,
            imageUrl: data.imageUrl,
            pageUrl: `https://numberblocks.fandom.com/wiki/${startNumber}`,
            aiGenerated: data.aiGenerated || false,
            generationMethod,
            svgGenerated: data.svgGenerated || false,
          }],
        };
      }
      return { success: false, error: data?.error || 'Generation failed' };
    }

    // For auto/wiki-only, use the scraper with strategy param
    const { data, error } = await supabase.functions.invoke('scrape-numberblocks', {
      body: { startNumber, endNumber, isSingleNumber, strategy },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async generateWithAI(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-numberblock', {
      body: { number },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async regenerate(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-numberblock', {
      body: { number, force: true },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async generateSVG(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-svg-numberblock', {
      body: { number },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async generateWithGemini(number: number): Promise<GenerateResponse> {
    const { data, error } = await supabase.functions.invoke('generate-gemini-numberblock', {
      body: { number },
    });

    if (error) {
      return { success: false, error: error.message };
    }
    
    return data;
  },

  async compareAllStrategies(number: number): Promise<{ strategy: GenerationStrategy; result: ScrapeResponse }[]> {
    const strategies = ALL_STRATEGIES;
    const promises = strategies.map(async (s) => {
      const result = await numberblocksApi.scrapeImages(number, number, s.value);
      return { strategy: s.value, result };
    });
    return Promise.all(promises);
  },
};
