import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

interface NumberImage {
  number: number;
  imageUrl: string | null;
  pageUrl: string;
  cached?: boolean;
  error?: string;
  aiGenerated?: boolean;
  generationMethod?: 'openai' | 'gemini';
  skipScrape?: boolean;
  autoGenerated?: boolean;
  composed?: boolean;
}

interface CacheEntry {
  number: number;
  storage_path: string;
}

// Rate limit configuration
const RATE_LIMITS = {
  perIp: {
    threshold: 20,
    strictThreshold: 0,
    windowMs: 5 * 60 * 1000,
    delayPerExcess: 10000,
  },
  global: {
    threshold: 100,
    windowMs: 60 * 1000,
    delayPerExcess: 5000,
  },
  maxDelay: 60000,
};

// Countries that get the strict per-IP threshold (suspected bot/scraper traffic).
const STRICT_COUNTRIES = new Set(['CN']);

// ============= Smart Scraping Helpers =============

function isPowerOf2(n: number): boolean {
  return n > 0 && (n & (n - 1)) === 0;
}

function isPowerOf10(n: number): boolean {
  if (n < 10) return false;
  let num = n;
  while (num >= 10) {
    if (num % 10 !== 0) return false;
    num = num / 10;
  }
  return num === 1;
}

function hasRepeatingDigits(n: number): boolean {
  const str = n.toString();
  if (str.length < 2) return false;
  return str.split('').every(c => c === str[0]);
}

/**
 * Whether it is worth asking the wiki at all.
 *
 * We no longer guess which numbers are "special": every number up to 1000 gets
 * a real attempt, because the wiki title lookup below is a cheap API call and
 * "no page exists" is a real answer rather than a guess made up front.
 * Above 1000 only powers of ten plausibly have a page.
 */
function shouldScrape(num: number): boolean {
  if (num <= 1000) return true;
  return isPowerOf10(num);
}


// ============= AI Generation Helper =============

async function generateWithAI(
  number: number, 
  supabase: any,
  clientIP: string = 'unknown'
): Promise<{ success: boolean; imageUrl?: string; error?: string }> {
  const OPENAI_API_KEY = Deno.env.get('OPENAI_API_KEY');
  if (!OPENAI_API_KEY) {
    return { success: false, error: 'OPENAI_API_KEY is not configured' };
  }

  // Check AI generation rate limits (shared with generate-numberblock endpoint)
  const aiRateLimits = {
    perIp: { threshold: 10, windowMs: 10 * 60 * 1000, delayPerExcess: 15000 },
    global: { threshold: 50, windowMs: 10 * 60 * 1000, delayPerExcess: 10000 },
    maxDelay: 60000,
  };

  const now = new Date();
  const aiWindowStart = new Date(now.getTime() - aiRateLimits.perIp.windowMs);
  
  const { data: ipGenCalls } = await supabase
    .from('rate_limit_log')
    .select('api_calls_count')
    .eq('ip_address', clientIP)
    .eq('endpoint', 'generate-numberblock')
    .gte('created_at', aiWindowStart.toISOString());
  
  const ipGenTotal = ipGenCalls?.reduce((sum: number, r: { api_calls_count: number }) => sum + r.api_calls_count, 0) || 0;
  
  const { data: globalGenCalls } = await supabase
    .from('rate_limit_log')
    .select('api_calls_count')
    .eq('endpoint', 'generate-numberblock')
    .gte('created_at', aiWindowStart.toISOString());
  
  const globalGenTotal = globalGenCalls?.reduce((sum: number, r: { api_calls_count: number }) => sum + r.api_calls_count, 0) || 0;

  let genDelay = 0;
  if (ipGenTotal > aiRateLimits.perIp.threshold) {
    genDelay += (ipGenTotal - aiRateLimits.perIp.threshold) * aiRateLimits.perIp.delayPerExcess;
  }
  if (globalGenTotal > aiRateLimits.global.threshold) {
    genDelay += (globalGenTotal - aiRateLimits.global.threshold) * aiRateLimits.global.delayPerExcess;
  }
  genDelay = Math.min(genDelay, aiRateLimits.maxDelay);

  if (genDelay > 0) {
    console.log(`AI generation rate limited: IP=${clientIP}, ipTotal=${ipGenTotal}, globalTotal=${globalGenTotal}, delay=${genDelay}ms`);
    await new Promise(resolve => setTimeout(resolve, genDelay));
  }

  console.log(`Auto-generating AI image for Numberblock ${number} via OpenAI DALL-E 3`);

  try {
    const numberWord = numberToWordForAI(number);
    const structureGuide = getStructureGuide(number);
    const bodyColor = getNumberblockColor(number);
    
    const prompt = `You are drawing a Numberblocks character: a figure made of cube blocks from the BBC show. The TOTAL number of visible blocks must EXACTLY equal ${number}. One face on the front only. The number (Numberling) appears on top. Black and white line art only, for a coloring page.

CRITICAL: The NUMBER OF BLOCKS MUST BE EXACTLY ${number} (${numberWord}).
Count carefully: ${number} blocks total, no more, no less.

BLOCK LAYOUT (MUST be clearly visible and countable):
${structureGuide}

VERIFICATION INSTRUCTION:
After drawing, verify that the TOTAL number of blocks visible equals EXACTLY ${number}.
If you draw ${number <= 100 ? "each cube" : "the structural units"}, count them to ensure correctness.

CHARACTER DESIGN:
- The entire body is made of visible cube blocks in the arrangement above; each block is a small cube.
- Exactly ONE face on the front of the block structure: two simple eyes and a smile. No faces on side blocks.
- Draw the digit "${number.toLocaleString()}" on top of the character (above the blocks), bold and clear, like the show's Numberling.
- No arms or legs, OR very simple rounded limbs only (no stick figures).
- Use a single body color: ${bodyColor}. Draw as black outline only for coloring.

STRICT RULES:
- TOTAL block count MUST be ${number} - verify by counting
- Add NO extra blocks, NO missing blocks
- NO scenery, backgrounds, rainbows, or extra characters
- Number "${number.toLocaleString()}" must be on TOP of the blocks, not on the side or corner
- Only ONE face on the front, NO multiple faces
- Black outline ONLY - no shading, gradients, or detailed texture
- Static image - NO animation, NO GIF effects, NO motion

Result: one Numberblocks character, black and white line art, coloring page style, no background, EXACTLY ${number} blocks.`;

    const response = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        // dall-e-3 has been retired by OpenAI; gpt-image-1-mini is the
        // current cost-efficient image model on the same endpoint.
        model: 'gpt-image-1-mini',
        prompt,
        n: 1,
        size: '1024x1024',
        quality: 'low',
      }),
    });


    if (!response.ok) {
      if (response.status === 429) {
        return { success: false, error: 'Rate limit exceeded' };
      }
      const errorText = await response.text();
      console.error('OpenAI DALL-E error:', response.status, errorText);
      return { success: false, error: 'Failed to generate image' };
    }

    const data = await response.json();
    // The images endpoint may return either inline base64 or a hosted URL
    // depending on the model, so support both instead of forcing a
    // response_format the endpoint may reject.
    let bytes: Uint8Array | null = null;
    const base64Data = data.data?.[0]?.b64_json;
    const imageUrlFromApi = data.data?.[0]?.url;

    if (base64Data) {
      const binaryString = atob(base64Data);
      bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
    } else if (imageUrlFromApi) {
      const imgResponse = await fetch(imageUrlFromApi);
      if (imgResponse.ok) {
        bytes = new Uint8Array(await imgResponse.arrayBuffer());
      }
    }

    if (!bytes) {
      console.error('No image in response:', JSON.stringify(data));
      return { success: false, error: 'No image generated' };
    }

    // DALL-E returns PNG images
    const imageType = 'png';


    const paddedNum = number.toString().padStart(3, '0');
    const storagePath = `ai-${paddedNum}.${imageType}`;
    
    const { error: uploadError } = await supabase.storage
      .from('numberblocks-images')
      .upload(storagePath, bytes, {
        contentType: `image/${imageType}`,
        upsert: true,
      });

    if (uploadError) {
      console.error('Storage upload error:', uploadError);
      return { success: false, error: 'Failed to save image' };
    }

    await supabase
      .from('numberblocks_cache')
      .upsert({
        number: number,
        storage_path: storagePath,
        original_url: 'ai-generated',
      }, { onConflict: 'number' });

    const { data: { publicUrl } } = supabase.storage
      .from('numberblocks-images')
      .getPublicUrl(storagePath);

    // Log AI generation call for rate limiting (shared endpoint with generate-numberblock)
    await logApiCalls(supabase, clientIP, 1, 'generate-numberblock');

    console.log(`Auto-generated AI image for ${number} saved at ${storagePath}`);
    
    return { success: true, imageUrl: publicUrl };
  } catch (error) {
    console.error('AI generation error:', error);
    return { success: false, error: error instanceof Error ? error.message : 'Unknown error' };
  }
}

// Canonical Numberblocks character colors (1-10 from the show); 11+ use single color.
function getNumberblockColor(num: number): string {
  const colors: Record<number, string> = {
    1: 'red', 2: 'orange', 3: 'yellow', 4: 'green', 5: 'blue',
    6: 'purple', 7: 'indigo', 8: 'pink', 9: 'teal', 10: 'light gray or white',
  };
  return colors[num] ?? 'single color';
}

// ============= Rate Limiting =============

function getClientIP(req: Request): string {
  return req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() 
    || req.headers.get('cf-connecting-ip') 
    || req.headers.get('x-real-ip')
    || 'unknown';
}

function getCountry(req: Request): string {
  return (req.headers.get('cf-ipcountry')
    || req.headers.get('x-country-code')
    || req.headers.get('x-vercel-ip-country')
    || 'unknown').toUpperCase();
}

function getPerIpThreshold(country: string): number {
  return STRICT_COUNTRIES.has(country)
    ? RATE_LIMITS.perIp.strictThreshold
    : RATE_LIMITS.perIp.threshold;
}

async function checkRateLimits(supabase: any, ip: string, country: string): Promise<{ delay: number; ipTotal: number; globalTotal: number; perIpThreshold: number }> {
  const now = new Date();
  const perIpThreshold = getPerIpThreshold(country);
  
  const ipWindowStart = new Date(now.getTime() - RATE_LIMITS.perIp.windowMs);
  const { data: ipCalls } = await supabase
    .from('rate_limit_log')
    .select('api_calls_count')
    .eq('ip_address', ip)
    .gte('created_at', ipWindowStart.toISOString());
  
  const ipTotal = ipCalls?.reduce((sum: number, r: { api_calls_count: number }) => sum + r.api_calls_count, 0) || 0;
  
  const globalWindowStart = new Date(now.getTime() - RATE_LIMITS.global.windowMs);
  const { data: globalCalls } = await supabase
    .from('rate_limit_log')
    .select('api_calls_count')
    .gte('created_at', globalWindowStart.toISOString());
  
  const globalTotal = globalCalls?.reduce((sum: number, r: { api_calls_count: number }) => sum + r.api_calls_count, 0) || 0;
  
  let delay = 0;
  if (ipTotal > perIpThreshold) {
    delay += (ipTotal - perIpThreshold) * RATE_LIMITS.perIp.delayPerExcess;
  }
  if (globalTotal > RATE_LIMITS.global.threshold) {
    delay += (globalTotal - RATE_LIMITS.global.threshold) * RATE_LIMITS.global.delayPerExcess;
  }
  
  return { 
    delay: Math.min(delay, RATE_LIMITS.maxDelay),
    ipTotal,
    globalTotal,
    perIpThreshold,
  };
}

async function logApiCalls(supabase: any, ip: string, count: number, endpoint: string = 'scrape-numberblocks'): Promise<void> {
  if (count <= 0) return;
  
  const { error } = await supabase.from('rate_limit_log').insert({
    ip_address: ip,
    endpoint,
    api_calls_count: count,
  });
  
  if (error) {
    console.error('Failed to log API calls:', error);
  }
}

async function cleanupOldRateLimitLogs(supabase: any): Promise<void> {
  const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000);
  
  const { error } = await supabase
    .from('rate_limit_log')
    .delete()
    .lt('created_at', oneHourAgo.toISOString());
  
  if (error) {
    console.error('Failed to cleanup old rate limit logs:', error);
  }
}

// ============= Main Handler =============

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const apiKey = Deno.env.get('FIRECRAWL_API_KEY');
    if (!apiKey) {
      console.error('FIRECRAWL_API_KEY not configured');
      return new Response(
        JSON.stringify({ success: false, error: 'Firecrawl connector not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const clientIP = getClientIP(req);
    const country = getCountry(req);
    const body = await req.json();
    const startNumber = body.startNumber ?? 1;
    const endNumber = body.endNumber ?? 20;
    const isSingleNumber = body.isSingleNumber ?? (startNumber === endNumber);
    const strategy = body.strategy ?? 'auto';

    // Input validation
    const MAX_RANGE = 50;
    
    if (typeof startNumber !== 'number' || typeof endNumber !== 'number' ||
        !Number.isFinite(startNumber) || !Number.isFinite(endNumber)) {
      return new Response(
        JSON.stringify({ success: false, error: 'Start and end numbers must be valid numbers' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!Number.isInteger(startNumber) || !Number.isInteger(endNumber)) {
      return new Response(
        JSON.stringify({ success: false, error: 'Numbers must be whole integers' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (startNumber < 0 || endNumber < 0) {
      return new Response(
        JSON.stringify({ success: false, error: 'Numbers must be 0 or greater' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (startNumber > endNumber) {
      return new Response(
        JSON.stringify({ success: false, error: 'Start number must be less than or equal to end number' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (endNumber - startNumber + 1 > MAX_RANGE) {
      return new Response(
        JSON.stringify({ success: false, error: `Maximum range is ${MAX_RANGE} numbers per request` }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    console.log(`Processing Numberblocks images from ${startNumber} to ${endNumber} (IP: ${clientIP}, singleNumber: ${isSingleNumber})`);
    
    // Check which numbers are already cached
    const { data: cachedEntries } = await supabase
      .from('numberblocks_cache')
      .select('number, storage_path')
      .gte('number', startNumber)
      .lte('number', endNumber);
    
    const cachedMap = new Map<number, string>();
    if (cachedEntries) {
      for (const entry of cachedEntries) {
        cachedMap.set(entry.number, entry.storage_path);
      }
    }
    
    console.log(`Found ${cachedMap.size} cached images`);
    
    const results: NumberImage[] = [];
    const numbersToScrape: number[] = [];
    
    // Build list of numbers to scrape vs return from cache vs skip
    for (let num = startNumber; num <= endNumber; num++) {
      if (cachedMap.has(num)) {
        // Return from cache
        const storagePath = cachedMap.get(num)!;
        const { data: { publicUrl } } = supabase.storage
          .from('numberblocks-images')
          .getPublicUrl(storagePath);
        
        const isAIGenerated = storagePath.startsWith('ai-') || storagePath.startsWith('gem-');
        const isComposed = storagePath.startsWith('comp-');
        const generationMethod = storagePath.startsWith('ai-') ? 'openai' as const
          : storagePath.startsWith('gem-') ? 'gemini' as const
          : undefined;
        
        results.push({
          number: num,
          imageUrl: publicUrl,
          pageUrl: `https://numberblocks.fandom.com/wiki/${numberToWord(num)}`,
          cached: true,
          aiGenerated: isAIGenerated,
          generationMethod,
          composed: isComposed,
        });
      } else if (!shouldScrape(num)) {
        // Skip scraping for non-special numbers
        console.log(`Skipping scrape for ${num} (not a special number)`);
        results.push({
          number: num,
          imageUrl: null,
          pageUrl: `https://numberblocks.fandom.com/wiki/${numberToWord(num)}`,
          error: 'Not expected to have wiki image',
          skipScrape: true,
        });
      } else {
        numbersToScrape.push(num);
      }
    }
    
    console.log(`Need to scrape ${numbersToScrape.length} new images (${results.filter(r => r.skipScrape).length} skipped as non-special)`);

    let wasThrottled = false;
    let appliedDelay = 0;
    
    // Only check rate limits if we need to make API calls
    if (numbersToScrape.length > 0) {
      const { delay, ipTotal, globalTotal, perIpThreshold } = await checkRateLimits(supabase, clientIP, country);
      
      if (delay > 0) {
        wasThrottled = true;
        appliedDelay = delay;
        console.log(`Rate limiting: IP=${clientIP}, country=${country}, ipTotal=${ipTotal}/${perIpThreshold}, globalTotal=${globalTotal}, delay=${delay}ms`);
        await new Promise(resolve => setTimeout(resolve, delay));
      }
      
      const batchSize = 5;
      let apiCallsCount = 0;
      
      for (let i = 0; i < numbersToScrape.length; i += batchSize) {
        const batch = numbersToScrape.slice(i, i + batchSize);
        const batchPromises = batch.map(num => scrapeAndCacheNumber(num, apiKey, supabase, supabaseUrl));
        
        const batchResults = await Promise.all(batchPromises);
        results.push(...batchResults);
        apiCallsCount += batch.length;
        
        if (i + batchSize < numbersToScrape.length) {
          await new Promise(resolve => setTimeout(resolve, 1000));
        }
      }
      
      await logApiCalls(supabase, clientIP, apiCallsCount);
      
      if (Math.random() < 0.01) {
        cleanupOldRateLimitLogs(supabase).catch(console.error);
      }
    }
    
    // Auto-generate for single number if no image found (skip if wiki-only strategy)
    if (isSingleNumber && strategy !== 'wiki-only') {
      const singleResult = results.find(r => r.number === startNumber);
      if (singleResult && !singleResult.imageUrl && !singleResult.cached) {
        // For numbers > 10, try composition first
        if (startNumber > 10) {
          console.log(`Trying composition first for single number ${startNumber}`);
          try {
            const composeResponse = await fetch(`${supabaseUrl}/functions/v1/compose-numberblock`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${supabaseServiceKey}`,
              },
              body: JSON.stringify({ number: startNumber }),
            });
            const composeData = await composeResponse.json();
            if (composeData.success && composeData.imageUrl) {
              singleResult.imageUrl = composeData.imageUrl;
              singleResult.composed = true;
              singleResult.autoGenerated = true;
              singleResult.error = undefined;
              singleResult.skipScrape = undefined;
              console.log(`Composition succeeded for ${startNumber}`);
            } else {
              console.log(`Composition failed for ${startNumber}, falling back to AI: ${composeData.error}`);
            }
          } catch (error) {
            console.log(`Composition error for ${startNumber}:`, error);
          }
        }

        // Fall back to AI generation if composition didn't work
        if (!singleResult.imageUrl) {
          console.log(`Auto-generating AI image for single number ${startNumber}`);
          const generated = await generateWithAI(startNumber, supabase, clientIP);
          if (generated.success && generated.imageUrl) {
            singleResult.imageUrl = generated.imageUrl;
            singleResult.aiGenerated = true;
            singleResult.generationMethod = 'openai';
            singleResult.autoGenerated = true;
            singleResult.error = undefined;
            singleResult.skipScrape = undefined;
          }
        }
      }
    }
    
    // Sort results by number
    results.sort((a, b) => a.number - b.number);

    const successCount = results.filter(r => r.imageUrl).length;
    const cachedCount = results.filter(r => r.cached).length;
    const skippedCount = results.filter(r => r.skipScrape).length;
    const autoGeneratedCount = results.filter(r => r.autoGenerated).length;
    console.log(`Returning ${results.length} images (${cachedCount} cached, ${successCount - cachedCount} newly scraped, ${skippedCount} skipped, ${autoGeneratedCount} auto-generated)`);

    const responseHeaders = { 
      ...corsHeaders, 
      'Content-Type': 'application/json',
      'X-Rate-Limited': wasThrottled ? 'true' : 'false',
      'X-Rate-Limit-Delay': appliedDelay.toString(),
    };

    return new Response(
      JSON.stringify({ 
        success: true, 
        data: results,
        rateLimited: wasThrottled,
        delayApplied: appliedDelay,
      }),
      { headers: responseHeaders }
    );
  } catch (error) {
    console.error('Error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to process';
    return new Response(
      JSON.stringify({ success: false, error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

/**
 * Ask the wiki itself which page titles actually exist, instead of guessing at
 * URL shapes. Returns candidate article URLs in preference order.
 */
async function resolveWikiPages(num: number): Promise<string[]> {
  const numberWord = numberToWord(num);
  const candidates = [
    `${numberWord}_(character)`,
    numberWord,
    `${numberWord}_(number)`,
    `${num}_(character)`,
    `${num}`,
  ];

  const api = `https://numberblocks.fandom.com/api.php?action=query&format=json&redirects=1&titles=${
    encodeURIComponent(candidates.join('|'))
  }`;

  try {
    const res = await fetch(api, {
      headers: { 'User-Agent': 'NumberblockFinder/1.0 (educational app)' },
    });
    if (res.ok) {
      const json = await res.json();
      const pages = json?.query?.pages ?? {};
      const existing: string[] = [];
      for (const key of Object.keys(pages)) {
        const page = pages[key];
        if (Number(key) > 0 && page?.title && page.missing === undefined) {
          existing.push(page.title as string);
        }
      }
      if (existing.length > 0) {
        // Preserve our preference order
        const rank = (title: string) => {
          const normalized = title.replace(/ /g, '_');
          const idx = candidates.indexOf(normalized);
          return idx === -1 ? 99 : idx;
        };
        existing.sort((a, b) => rank(a) - rank(b));
        return existing.map(
          (t) => `https://numberblocks.fandom.com/wiki/${encodeURIComponent(t.replace(/ /g, '_'))}`,
        );
      }
      console.log(`Wiki has no page for ${num}`);
      return [];
    }
    console.error(`Wiki title lookup failed for ${num}: ${res.status}`);
  } catch (error) {
    console.error(`Wiki title lookup error for ${num}:`, error);
  }

  // Lookup unavailable - fall back to the constructed title so we still try.
  return [`https://numberblocks.fandom.com/wiki/${encodeURIComponent(numberWord)}`];
}

async function firecrawlHtml(url: string, apiKey: string): Promise<string | null> {
  try {
    const response = await fetch('https://api.firecrawl.dev/v1/scrape', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ url, formats: ['html', 'links'], onlyMainContent: false }),
    });
    const data = await response.json();
    if (!response.ok) {
      console.error(`Firecrawl error for ${url}:`, data?.error || response.status);
      return null;
    }
    return data.data?.html || data.html || '';
  } catch (error) {
    console.error(`Firecrawl fetch error for ${url}:`, error);
    return null;
  }
}

async function scrapeAndCacheNumber(num: number, apiKey: string, supabase: any, supabaseUrl: string): Promise<NumberImage> {
  const numberWord = numberToWord(num);
  const resolved = await resolveWikiPages(num);
  const pageUrl = resolved[0] ?? `https://numberblocks.fandom.com/wiki/${encodeURIComponent(numberWord)}`;

  if (resolved.length === 0) {
    // A real, definitive negative: the wiki simply has no article for this number.
    return { number: num, imageUrl: null, pageUrl, error: 'No wiki page for this number' };
  }

  try {
    let originalImageUrl: string | null = null;

    // Try each real article, then its gallery subpage. Only accept an image
    // that positively matches the number (exact filename token or infobox
    // position) - no "first image on the page" guessing, no loose fan-art match.
    for (const articleUrl of resolved) {
      console.log(`Scraping: ${articleUrl}`);
      const html = await firecrawlHtml(articleUrl, apiKey);
      if (!html) continue;
      if (isDisambiguationPage(html)) {
        console.log(`Disambiguation page for ${num}, trying next candidate`);
        continue;
      }

      originalImageUrl = extractInfoboxImage(html, num, true) ?? extractInfoboxImageFallback(html, num);
      if (originalImageUrl) break;

      const galleryHtml = await firecrawlHtml(`${articleUrl}/Gallery`, apiKey);
      if (galleryHtml && galleryHtml.length > 500) {
        originalImageUrl = extractInfoboxImageFallback(galleryHtml, num);
        if (originalImageUrl) {
          console.log(`Found number-matched gallery image for ${num}`);
          break;
        }
      }
    }

    if (!originalImageUrl) {
      return { number: num, imageUrl: null, pageUrl, error: 'No image found' };
    }

    const imageResponse = await fetch(originalImageUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        'Referer': 'https://numberblocks.fandom.com/',
      },
    });

    if (!imageResponse.ok) {
      console.error(`Failed to download image for ${num}: ${imageResponse.status}`);
      return { number: num, imageUrl: null, pageUrl, error: 'Image download failed' };
    }

    const contentType = imageResponse.headers.get('content-type') || 'image/png';
    const imageData = new Uint8Array(await imageResponse.arrayBuffer());

    // Verify before caching: a wrong picture cached once is wrong forever.
    const verification = await verifyImageBytes(imageData, contentType, num);
    if (!verification.verified && !verification.skipped) {
      console.log(`Scraped image for ${num} rejected by verifier: ${verification.note}`);
      return {
        number: num,
        imageUrl: null,
        pageUrl,
        error: `Wiki image failed verification (${verification.note})`,
      };
    }

    let extension = 'png';
    if (contentType.includes('jpeg') || contentType.includes('jpg')) extension = 'jpg';
    else if (contentType.includes('gif')) extension = 'gif';
    else if (contentType.includes('webp')) extension = 'webp';

    const paddedNum = num.toString().padStart(3, '0');
    const storagePath = `${paddedNum}.${extension}`;

    const { error: uploadError } = await supabase.storage
      .from('numberblocks-images')
      .upload(storagePath, imageData, {
        contentType,
        upsert: true,
      });

    if (uploadError) {
      console.error(`Failed to cache image ${num}:`, uploadError);
      return { number: num, imageUrl: originalImageUrl, pageUrl };
    }

    await supabase
      .from('numberblocks_cache')
      .upsert({
        number: num,
        storage_path: storagePath,
        original_url: originalImageUrl,
        source: 'wiki',
        model: null,
        verified: verification.verified,
        verification_note: verification.note,
        verified_at: new Date().toISOString(),
      }, { onConflict: 'number' });

    const { data: { publicUrl } } = supabase.storage
      .from('numberblocks-images')
      .getPublicUrl(storagePath);

    console.log(`Cached image ${num} at ${storagePath} (verified: ${verification.verified})`);

    return { number: num, imageUrl: publicUrl, pageUrl, cached: true, source: 'wiki', verified: verification.verified };
  } catch (error) {
    console.error(`Error processing ${num}:`, error);
    return { 
      number: num, 
      imageUrl: null, 
      pageUrl, 
      error: error instanceof Error ? error.message : 'Unknown error' 
    };
  }
}


function isDisambiguationPage(html: string): boolean {
  const lower = html.toLowerCase();
  return lower.includes('may refer to') || 
         lower.includes('disambiguation') || 
         lower.includes('disambiguations');
}

function isValidCharacterImage(imageUrl: string): boolean {
  const invalidPatterns = [
    /placeholder/i,
    /icon/i,
    /favicon/i,
    /logo/i,
    /banner/i,
    /Site-logo/i,
    /Wiki-wordmark/i,
    /Community-header/i,
    /avatar/i,
    /badge/i,
    /button/i,
    /sprite/i,
    /Blocks_Universe/i,
    /BLOCKS.*UNIVERSE/i,
    /community/i,
    /wiki.*wordmark/i,
  ];
  
  for (const pattern of invalidPatterns) {
    if (pattern.test(imageUrl)) {
      return false;
    }
  }
  
  if (!imageUrl.includes('static.wikia.nocookie.net/numberblocks/images')) {
    return false;
  }
  
  return true;
}

// Extract image URLs from <img> tags. Wiki pages lazy-load images: the real URL
// lives in data-src while src holds a 1x1 placeholder GIF. We prefer data-src
// when present so we don't end up with placeholder pixels.
function extractImageSources(html: string): string[] {
  const urls: string[] = [];
  for (const match of html.matchAll(/<img\b[^>]*>/gi)) {
    const tag = match[0];
    const dataSrc = tag.match(/\bdata-src="([^"]+)"/i)?.[1];
    const src = tag.match(/\bsrc="([^"]+)"/i)?.[1];
    const chosen = (dataSrc && /^https?:/i.test(dataSrc)) ? dataSrc : src;
    if (chosen && /^https?:/i.test(chosen)) {
      urls.push(chosen);
    }
  }
  return urls;
}

// Tokenize a filename into alphanumeric runs, separating digit runs from
// letter runs so we can match number tokens exactly (e.g. "100_is_big" =>
// ["100", "is", "big"], not "1" matching inside "100").
function tokenizeFilename(filename: string): string[] {
  const base = filename.split('?')[0].replace(/\.[a-z0-9]+$/i, '');
  return base.split(/[^a-z0-9]+|(?<=\d)(?=[a-z])|(?<=[a-z])(?=\d)/i).filter(Boolean);
}

// Wikia URLs look like .../images/9/9c/One.png/revision/latest/scale-to-width-down/200?cb=...
// The actual filename is the segment immediately before /revision/, NOT the last URL segment.
function getWikiFilename(imageUrl: string): string {
  const noQuery = imageUrl.split('?')[0];
  const beforeRevision = noQuery.split('/revision/')[0];
  return beforeRevision.split('/').pop() || '';
}

function normalizeWikiImageUrl(imageUrl: string): string {
  return imageUrl
    .replace(/\/revision\/latest\/scale-to-width-down\/\d+/, '/revision/latest')
    .replace(/\/revision\/latest\/smart\/width\/\d+\/height\/\d+/, '/revision/latest');
}

function extractInfoboxImage(html: string, num: number, skipFallback: boolean = false): string | null {
  const numStr = num.toString();
  const numWithCommas = num.toLocaleString().replace(/,/g, '');
  const allUrls = extractImageSources(html);

  // Priority 1: Look for images whose filename has the exact number as a token
  // (not a substring). This avoids "100_is_big.png" matching when num=1.
  for (const url of allUrls) {
    if (!isValidCharacterImage(url)) continue;
    const filename = getWikiFilename(url);
    const tokens = tokenizeFilename(filename);
    if (tokens.includes(numStr) || tokens.includes(numWithCommas)) {
      return normalizeWikiImageUrl(url);
    }
  }
  
  // Priority 2: For small numbers, try the infobox patterns
  if (num <= 1000) {
    const infoboxPatterns = [
      /class="pi-image[^"]*"[^>]*>[\s\S]*?<img\b([^>]*)>/i,
      /<aside\b[^>]*class="[^"]*infobox[^"]*"[^>]*>[\s\S]*?<img\b([^>]*)>/i,
    ];

    for (const pattern of infoboxPatterns) {
      const match = html.match(pattern);
      if (match && match[1]) {
        const attrs = match[1];
        const dataSrc = attrs.match(/\bdata-src="([^"]+)"/i)?.[1];
        const src = attrs.match(/\bsrc="([^"]+)"/i)?.[1];
        const imageUrl = (dataSrc && /^https?:/i.test(dataSrc)) ? dataSrc : src;
        if (imageUrl && isValidCharacterImage(imageUrl)) {
          return normalizeWikiImageUrl(imageUrl);
        }
      }
    }
    
    // Priority 3: Fallback - check if filename contains number word (fan art territory)
    if (!skipFallback) {
      return extractInfoboxImageFallback(html, num);
    }
  }

  return null;
}

// Separate fallback function: Priority 3 - filename matches number word as a token.
// Example: for num=1, accept "One.png" but reject "Square_Cork_Shaped_One.PNG"
// (we want the canonical short filename, not modifier-laden variants).
function extractInfoboxImageFallback(html: string, num: number): string | null {
  if (num > 1000) return null;
  
  const numberName = numberToWord(num).toLowerCase().replace(/[_-]/g, '');
  const allUrls = extractImageSources(html);

  // First pass: filename is exactly the number word (e.g. "One.png")
  for (const url of allUrls) {
    if (!isValidCharacterImage(url)) continue;
    const filename = getWikiFilename(url).replace(/\.[a-z0-9]+$/i, '');
    if (filename.toLowerCase() === numberName) {
      return normalizeWikiImageUrl(url);
    }
  }

  // Second pass: filename contains number word as a token (looser, fan-art territory)
  for (const url of allUrls) {
    if (!isValidCharacterImage(url)) continue;
    const filename = getWikiFilename(url);
    const tokens = tokenizeFilename(filename).map(t => t.toLowerCase());
    if (tokens.includes(numberName)) {
      return normalizeWikiImageUrl(url);
    }
  }
  
  return null;
}

// Extract first valid character image from a Gallery page
function extractFirstGalleryImage(html: string, num: number): string | null {
  const allUrls = extractImageSources(html);
  for (const url of allUrls) {
    if (!isValidCharacterImage(url)) continue;
    return normalizeWikiImageUrl(url);
  }
  return null;
}

function numberToWord(num: number): string {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
                'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 
                'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  
  if (num === 0) return 'Zero';
  if (num < 20) return ones[num];
  if (num < 100) {
    const ten = Math.floor(num / 10);
    const one = num % 10;
    return tens[ten] + (one > 0 ? '-' + ones[one].toLowerCase() : '');
  }
  if (num === 100) return 'One_Hundred';
  if (num > 100 && num < 1000) {
    const hundred = Math.floor(num / 100);
    const remainder = num % 100;
    if (remainder === 0) {
      return ones[hundred] + '_Hundred';
    }
    return ones[hundred] + '_Hundred_' + numberToWord(remainder).replace('-', '_');
  }
  if (num === 1000) return 'One_Thousand';
  
  return num.toString();
}

// Version for AI prompts (readable format)
function numberToWordForAI(num: number): string {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
                'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 
                'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  
  if (num === 0) return 'Zero';
  if (num < 20) return ones[num];
  if (num < 100) {
    const ten = Math.floor(num / 10);
    const one = num % 10;
    return tens[ten] + (one > 0 ? '-' + ones[one].toLowerCase() : '');
  }
  if (num === 100) return 'One Hundred';
  if (num > 100 && num < 1000) {
    const hundred = Math.floor(num / 100);
    const remainder = num % 100;
    if (remainder === 0) {
      return ones[hundred] + ' Hundred';
    }
    return ones[hundred] + ' Hundred ' + numberToWordForAI(remainder);
  }
  if (num === 1000) return 'One Thousand';
  if (num >= 1000 && num < 1000000) {
    const thousands = Math.floor(num / 1000);
    const remainder = num % 1000;
    if (remainder === 0) {
      return numberToWordForAI(thousands) + ' Thousand';
    }
    return numberToWordForAI(thousands) + ' Thousand ' + numberToWordForAI(remainder);
  }
  if (num >= 1000000) {
    const millions = Math.floor(num / 1000000);
    const remainder = num % 1000000;
    if (remainder === 0) {
      return numberToWordForAI(millions) + ' Million';
    }
    return numberToWordForAI(millions) + ' Million ' + numberToWordForAI(remainder);
  }
  
  return num.toLocaleString();
}

function getStructureGuide(num: number): string {
  if (num <= 9) {
    return `- Build as a simple stack or rectangle of exactly ${num} visible, countable cubes
- Each individual cube should be clearly visible and countable
- Arrange in a compact shape (e.g., ${getSmallNumberArrangement(num)})
- The child should be able to count every single block`;
  }
  
  if (num === 10) {
    return `- Show as a clean rectangle of 10 blocks (2 columns of 5, or 1 row of 10)
- Ten is the first "grouped unit" - make it look like a building block itself
- All 10 cubes should be visible but arranged as a unified shape`;
  }
  
  if (num <= 99) {
    const tensNum = Math.floor(num / 10);
    const onesNum = num % 10;
    const onesText = onesNum > 0 ? ` with ${onesNum} extra single block${onesNum > 1 ? 's' : ''} attached on the side or top` : '';
    return `- Build from ${tensNum} groups of ten${onesText}
- The tens form the main rectangular body
- Extra ones attach clearly and separately
- The viewer should "see" addition: ${tensNum}×10 + ${onesNum} = ${num}
- All blocks should still be individually visible`;
  }
  
  if (num === 100) {
    return `- Show as a large 10×10 square grid (100 blocks total)
- This is the first number where counting is impractical
- The structure should signal "hundred" through its grid pattern
- Individual cubes can be implied but the 10×10 structure must be clear`;
  }
  
  if (num <= 999) {
    const hundreds = Math.floor(num / 100);
    const remainder = num % 100;
    const remainderText = remainder > 0 ? ` plus visible extra blocks for the remaining ${remainder}` : '';
    return `- Show as ${hundreds} stacked or side-by-side 10×10 hundred-slabs${remainderText}
- Each hundred-slab keeps its 10×10 identity
- Structure is architectural - the count is implied by the pattern
- Think of it as ${hundreds} "hundred-blocks" combined`;
  }
  
  if (num <= 9999) {
    const thousands = Math.floor(num / 1000);
    const remainder = num % 1000;
    return `- Conceptualize as ${thousands} "thousand-blocks" (each is a cube of 10 hundred-slabs)
- Individual cubes cannot all be drawn - use structural representation
- Show the magnitude through HEIGHT and SCALE, not individual blocks
- ${remainder > 0 ? `Include visual indication of the extra ${remainder}` : 'Clean thousand-block structure'}
- Use mega-blocks arranged in clean grids and balanced rectangles`;
  }
  
  if (num <= 999999) {
    const mainUnit = Math.floor(num / 1000);
    return `- SYMBOLIC STRUCTURE: Impossible to show every cube
- Represent as ${mainUnit.toLocaleString()} thousand-blocks in a massive grid/tower
- Use repeating patterns of known shapes (tens, hundreds) to signal scale
- WIDTH and HEIGHT show magnitude, not literal cube count
- Think architectural monument, not countable blocks
- Clear visual hierarchy: the number is understood by STRUCTURE, not detail`;
  }
  
  return `- PURE STRUCTURE AND SCALE representation
- Show as a monumental tower or massive cube made of implied thousand-layers
- Individual blocks are completely abstracted into mega-structures
- Use labels, perspective, and sheer size to convey magnitude
- The character should feel MASSIVE and architectural
- Think skyscraper or mountain-sized, with structure implying the count`;
}

function getSmallNumberArrangement(num: number): string {
  switch (num) {
    case 1: return '1 single cube';
    case 2: return '2 cubes stacked vertically or side-by-side';
    case 3: return '3 cubes in a triangle or row';
    case 4: return '2×2 square';
    case 5: return '5 cubes in a plus shape or row';
    case 6: return '2×3 rectangle';
    case 7: return '2×3 + 1 on top';
    case 8: return '2×4 rectangle or 2×2×2 cube';
    case 9: return '3×3 square';
    default: return `${num} cubes arranged compactly`;
  }
}
